package com.mcheungsen.Problems;

import com.mcheungsen.EulerProblem;

public class Problem2 implements EulerProblem {
    /**
     * Each new term in the Fibonacci sequence is generated by adding the
     * previous two terms. By starting with 1 and 2, the first 1à terms will be :
     * 1,2,3,5,8,13,21,34,55,89
     *
     * By considering the terms in the Fibonacci sequence whose values do not exceed
     * four million, find the sum of the even-valued terms
     */

    @Override
    public int solve() {
        int res = 0;

        int current = 2;
        int previous = 1;
        int next;

        while (current <= 4000000){
            if(current % 2 == 0) res += current;

            next = previous + current;
            previous = current;
            current = next;
        }

        return res;
    }

    @Override
    public String getName() {
        return "Even Fibonacci Numbers";
    }
}
